dist: bionic
language: cpp
compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gcc-8 g++-8
  - sudo apt-get -y install qt5-default qt5-qmake libqt5charts5-dev libqt5serialport5-dev
  
